server: 
  port: 80

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/green-guardians
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
    continue-on-error: true