insert into master_user_role (role_name) VALUES ('SITE_ADMIN'), ('CONTENT_EDITOR'), ('SPONSOR');

insert into master_user_info (first_name, email_add, user_role_id) VALUES('Admin', 'ecominds7@gmail.com', 1), ('Riddhi', 'riddhi.8@gmail.com', 2), ('Madhu', 'madhumitabose09@gmail.com', 2), ('Gurmeet', 'gurmeetshire@gmail.com', 2), ('Rajiv', 'rajiv3124@gmail.com', 2), ('Atharva', 'ahardas30@gmail.com', 2);

--insert into master_project_info (project_name, project_title, short_desc, long_desc, img_url_path, project_initiator, target_amt, start_date, expected_closure_date) VALUES (project_name, project_title, short_desc, long_desc, img_url_path, project_initiator, target_amt, start_date, expected_closure_date);

insert into master_project_info (project_name, project_title, short_desc, long_desc, img_url_path, project_initiator, target_amt, start_date, expected_closure_date) VALUES ('Greenhouse emissions', 'Greenhouse Emissions – Carbon Neutrality', 'We tackled some of the biggest challenges of our era: the production of food, the eradication of diseases, and the expansion of transport and communication systems', 'Since the industrial revolution, technology has boosted the development of our societies in ways we never seen before. We tackled some of the biggest challenges of our era: the production of food, the eradication of diseases, and the expansion of transport and communication systems. But this form of development has come at a cost and has become, perhaps, the greatest threat of our time. The combustion of fossil like petrol, coal or gas, that fuelled the production, has released millions of tons of carbon gases to the atmosphere. These greenhouse gas emissions are in part reabsorbed by the oceans and forests. But their drastic increase over the past 50 years, combined with the deforestation from unsustainable agriculture, has caused a global warming effect: the average Earth temperature is 1°C warmer than it was before the industrial revolution. This increase might not seem much, but we have already seen its dramatic effects. Glaciers are melting, making the sea levels raise, coral reefs and marine biodiversity are disappearing as a result of the oceans warming up, fierce climate events occurring more and more frequently are putting food security at risk and destroying people’s houses, forcing them to flee.', 'img-001.jpg', 'Gurmeet', 25000, parsedatetime('2019-09-10 00:01:00.59', 'yyyy-MM-dd hh:mm:ss.SS'), parsedatetime('2019-09-11 00:01:00.59', 'yyyy-MM-dd hh:mm:ss.SS'));

insert into master_project_info (project_name, project_title, short_desc, long_desc, img_url_path, project_initiator, target_amt, start_date, expected_closure_date) VALUES ('Clean the ocean', 'Preserving Marine and Ocean Life', 'Preserving Marine and Ocean Life', 'The "world’s" oceans – their temperature, chemistry, currents and life – drive global systems that make the Earth habitable for humankind. How we manage this vital resource is essential for humanity as a whole, and to counterbalance the effects of climate change. Over three billion people depend on marine and coastal biodiversity for their livelihoods. However, today we are seeing 30 percent of the "world’s" fish stocks overexploited, reaching below the level at which they can produce sustainable yields. Oceans also absorb about 30 percent of the carbon dioxide produced by humans, and we are seeing a 26 percent rise in ocean acidification since the beginning of the industrial revolution. Marine pollution, an overwhelming majority of which comes from land-based sources, is reaching alarming levels, with an average of 13,000 pieces of plastic litter to be found on every square kilometre of ocean. The SDGs aim to sustainably manage and protect marie and coastal ecosystems from pollution, as well as address the impacts of ocean acidification. Enhancing conservation and the sustainable use of ocean-based resources through international law will also help mitigate some of the challenges facing our oceans.', 'img-002.jpg', 'JaiAgarwal', 55000, parsedatetime('2019-09-10 00:01:00.59', 'yyyy-MM-dd hh:mm:ss.SS'), parsedatetime('2019-09-11 00:01:00.59', 'yyyy-MM-dd hh:mm:ss.SS'));

insert into master_project_info (project_name, project_title, short_desc, long_desc, img_url_path, project_initiator, target_amt, start_date, expected_closure_date) VALUES ('Climate Change Reality', 'Blue Green Infrastructure - Integration with Climate change', 'Blue Green Infrastructure - Integration with Climate change', 'Climate change is real and is really happening.In summary, climate change can be summarized by 1) rising temperatures and 2) sea level rise, both of which will have drastic impacts on human existence. Prof Erland Källén, director of Meteorological Service Singapore, stressed how if humankind continues “Business-As-Usual” without changing our current actions, temperatures could potentially hit 40oC by 2050! Prof Benjamin Horton, Chair of the Asian School for the Environment from Nanyang Technological University,brought back the “Business-As-Usual” concept and stated that sea levels could potentially rise by a whole metre by 2100 if we do not change our ways. Climate change is expected to result in more intense and longer-lasting droughts and increase in the frequency and intensity of heavy rainfall events. The combination of drought followed by intense rainfall increases the risk of severe flooding, with impacts na range of natural and anthropogenic systems, including infrastructure (road washouts, damage to houses) and impacts on agriculture (soil erosion and loss of crops and livestock). Blue-Green Infrastructure (BGI) is an interconnected network of natural and designed landscape components, including water bodies and green and open spaces, which provide multiple functions such as: (i) water storage for irrigation and industry use, (ii) flood control,(iii) wetland areas for wildlife habitat or water purification, and many others.', 'img-003.jpg', 'Sushwar', 80000, parsedatetime('2019-09-10 00:01:00.59', 'yyyy-MM-dd hh:mm:ss.SS'), parsedatetime('2019-09-11 00:01:00.59', 'yyyy-MM-dd hh:mm:ss.SS'));

insert into master_site_settings (key_to_access, title, is_checked) VALUES ('showQueryEditor', 'Show Query Editor', 1), ('showLoginBtn', 'Show Login Button', 0), ('showTeamMembers', 'Show Team Members', 1), ('enableGoolgeAnalytics', 'Enable Google Analytics', 0);

INSERT INTO master_team_member (first_name, last_name, email_add, contact_no, gender, img_url_path, about_me) VALUES 
 ('Gurmeet', 'Shire', 'gurmeet.shire@db.com', '+91 95117 95335', 'M', 'gurmeet-128x128.jpg', 'As a technical architect, he is able to use his knack for problem solving to create valuable technology solutions while ensuring systems are performing as required. He brings this energy and ambition to his position every day, engaging with and learning from everyone'),
 ('Rajiv', 'Kumar', 'rajiv-b.kumar@db.com', '+91 9 7660 7661 7', 'M', 'rajiv-128x128.jpg', 'Technology Geek, expertize in conceptualizing, designing and coding technical solutions using Java/J2EE and Spring technology stacks'),
 ('Madhumita', 'Bose', 'madhumita.bose@db.com', '+91 84467 64501', 'F', 'madhu-128x128.jpg', 'A very lively techie who always keeps moral of the team high'),
 ('Riddhi', 'Kothari', 'riddhi-mukesh.kothari@db.com', '+91 89561 68069', 'F', 'riddhi-128x128.jpg', 'A complete mix of technolgy and process. In fact, she is our wikipedia'),
 ('Atharva', 'Hardas', 'atharva-arvind.hardas@db.com', '+91 99702 86557', 'M', 'atharva-128x128.jpg', 'A process orieneted techie, he is having a strategic view of defining the problems and the solutions.'),
 ('Jagdish', 'Joshi', 'jagdish.chandra-joshi@db.com', '+91 97114 11828', 'M', 'joshi-128x128.jpg', 'Analytics professional with diverse experience spanning sales operations, business intelligence, process automation &amp; MIS');